name: Build and Sign Windows App

on:
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest  # CAMBIADO: Necesitas Windows
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4  # ACTUALIZADO a v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4  # ACTUALIZADO a v4
      with:
          node-version: 20.x
    
    - name: Install dependencies
      run: cd harvester-app && npm install
    
    - name: Decodificar certificado
      env:
        CERTIFICATE_BASE64: ${{ secrets.WINDOWS_CERT_BASE64 }}
      run: |
        echo $env:CERTIFICATE_BASE64 | base64 -d > harvester-app/certificate.pfx
      shell: bash
    
    - name: Construir y firmar app
      env:
        WINDOWS_CERT_PASSWORD: ${{ secrets.WINDOWS_CERT_PASSWORD }}
        CI: true
      run: cd harvester-app && npm run make
    
    - name: Subir instalador
      uses: actions/upload-artifact@v4  # ACTUALIZADO a v4
      with:
        name: windows-installer
        path: |
          harvester-app/out/make/squirrel.windows/**/*.exe
          harvester-app/out/make/squirrel.windows/**/*.nupkg
          harvester-app/out/make/squirrel.windows/**/RELEASES